name: JUG Karlsruhe
description: JUg Karlsruhe

paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
paginate: 5
timezone: Europe/Berlin

navigation:
 - title: Home
   url: /index.html
 - title: Veranstaltungen
   url: /events
 - title: Hall of Fame
   url: /speakers
 - title: Ãœber uns
   url: /about
 - title: Kontakt
   url: /contact